### ISSUE TITLE
Registering a user without as provider

### ISSUE THREAD

**Issue by mhluzi** [adamwathan/eloquent-oauth-l5#1]
Hi Adam

I am a newcomer to Laravel 5  and was wondering if it was possible to use your package to simply register a user without going through any of the providers.

Currently I have the linkedin and facebook logins working smoothly and need to also be able to register and login a user just via their email/username/password.

Am I missing something simple perhaps?

Cheers

M

**Comment by adamwathan** [comment]
Hey! You can register users via email/username/password the same way you would before, just using the `Auth` facade or underlying `Guard` class. Just follow the docs [here](http://laravel.com/docs/5.0/authentication) and everything will work great and play nicely.

Any other questions just let me know, happy to help.

**Comment by mhluzi** [comment]
That's great - thanks so much!
