### ISSUE TITLE
publish package configuration in Laravel 5.1

### ISSUE THREAD

**Issue by Shemahmforash** [adamwathan/eloquent-oauth-l5#11]
After installing correctly the package and defining the provider and the facade, the command for publishing the package configuration `php artisan eloquent-oauth:install` is not working in my L5.1 project. It says:

```
[InvalidArgumentException]
There are no commands defined in the "eloquent-oauth" namespace.
```

Also tried with: `php artisan vendor:publish --provider="AdamWathan\EloquentOAuthL5\EloquentOAuthServiceProvider"`
which responds: `Nothing to publish for tag [].`

Is the package ready for Laravel 5.1, or am I doing anything wrong?

Thanks in advance.

**Comment by adamwathan** [comment]
Hmm working fine here, here's an example L5.1 project with the package installed and working, can you poke around and see if you notice anything different?

https://github.com/adamwathan/eloquent-oauth-l5-example

**Comment by Shemahmforash** [comment]
After running `php artisan config:clear`, I managed to publish the package and run the migration successfully.

Thanks for your help.
