### ISSUE TITLE
Displaying if user is logged in with social vs. Laravel login

### ISSUE THREAD

**Issue by jerauf** [adamwathan/eloquent-oauth-l5#12]
I'd like to be able to display a notification like "You are logged in using Facebook" on a profile page. And use that info in if statements as well. For example, they shouldn't be able to change their email address if they're using social login.

How do I check if they have an entry in oauth_identities without manually doing a query? Is there already a way using Auth::?

**Comment by adamwathan** [comment]
Nothing is built in to support this out of the box, but you could set it up yourself without too much trouble I think.

Try adding something like this to your User (depending on how your users column looks of course):

``` php
    public function getSource()
    {
        if ($this->email !== null && $this->password !== null) {
            return 'email';
        }

        $identity = AdamWathan\EloquentOAuth\OAuthIdentity::where('user_id', $this->id)->first();
        return $identity->provider;
    }
```

Should return `email` if someone has an email and password, or the name of the provider (like `facebook`) if they have an OAuthIdentity linked to their account.
