### ISSUE TITLE
Can we also get timezone?

### ISSUE THREAD

**Issue by BrendanTWhite** [adamwathan/eloquent-oauth-l5#13]
Facebook gives us the timezone (well, technically the timezone offset) but when I try to access `$details->timezone` in `OAuth::login('facebook', function($user, $details)` the timezone isn't there.

Am I missing something obvious?

**Comment by adamwathan** [comment]
Try `$details->raw('timezone')`. If it's available using the scopes that are setup, it should come back there.

It won't come back as part of the standardized response because not all social providers will include that and part of the goal of the package is to normalize the data across providers.

**Comment by BrendanTWhite** [comment]
Hi Adam, thanks for getting back to me so quick.

I tried that but it doesn't seem to be there. So I did `var_dump($details)` and it gave me:
![no_timezone](https://cloud.githubusercontent.com/assets/2833789/9062034/d9b31c90-3afe-11e5-9005-5162c793453b.png)

...so I guess it's not there. I'll go dig deeper, and if I find anything I'll post back.

**Comment by BrendanTWhite** [comment]
Looks like it's the `$fields` array in lines 14-17 of `socialnorm-facebook/src/FacebookProvider.php` that controls this. When I add 'timezone' to this array, I get the timezone in `$details->raw`.
![with_tz](https://cloud.githubusercontent.com/assets/2833789/9062444/9b41cfb2-3b01-11e5-9d73-97c6f9548dbb.png)

I'll post something in socialnorm.

Thanks again,
     B.

**Comment by adamwathan** [comment]
Ah makes sense!

You could easily extend the default Facebook provider and replace that fields array with your own, then just register your Facebook provider using this method: https://github.com/adamwathan/eloquent-oauth/blob/master/src/OAuthManager.php#L27-L30

Just register it under the `facebook` key and it'll override the one that's registered by default. I think if you put it in your `AppServiceProvider` it'll get registered last and definitely override the existing registration.

Would be nice to make the Facebook provider more configurable out of the box but this should help in the mean time.

**Comment by BrendanTWhite** [comment]
Cool - I'll give that a try. Many thanks for your help.  :-)

**Comment by BrendanTWhite** [comment]
In case anyone's ever looking at this, I've put together a [pull request](https://github.com/adamwathan/socialnorm-facebook/pull/2).
