### ISSUE TITLE
L5 wrapper documentation refer to the wrong exception class

### ISSUE THREAD

**Issue by ockam** [adamwathan/eloquent-oauth-l5#15]
Hi Adams,

just noticed that the wrapper doc still refer to the exception classes inside your package:

```
use \AdamWathan\EloquentOAuth\Exceptions\ApplicationRejectedException;
use \AdamWathan\EloquentOAuth\Exceptions\InvalidAuthorizationCodeException;
```

instead of

```
use SocialNorm\Exceptions\ApplicationRejectedException;
use SocialNorm\Exceptions\InvalidAuthorizationCodeException;
```

**Comment by adamwathan** [comment]
Whoops! Thank you :)

**Comment by ockam** [comment]
In the sample code, there’s also an error: replace `fullName`by `full_name`.

Maybe you should just link back to eloquent-oauth doc to avoid maintaining both. :)

**Comment by adamwathan** [comment]
Pffft why would I do something smart like that? :) Thanks, I'll definitely update that. I have a bunch of OS work I've been trying to make time for (doc cleanup on these packages is high on that list!) but it's just so hard to fit everything in :(
