### ISSUE TITLE
Not getting full profile information (linkedIn provider)

### ISSUE THREAD

**Issue by ockam** [adamwathan/eloquent-oauth-l5#16]
Hi Adam,

using the linkedIn provider and setting my scope to `['r_basicprofile', 'w_share']`, I asume I should receive [more informations](https://developer.linkedin.com/docs/fields/basic-profile]) in the raw array, but I get the same result I add when my scope was set to `'w_share'`.

I’m currently using the latest release on L5.1. 

Am I missing something here?

**Comment by ockam** [comment]
I don’t know if its related, but after further testing, I realised I have set my LinkedIn application default permission to `r_basicprofile`, `r_emailaddress` and `w_share`.

Adding `r_basicprofile` to my scope just duplicate the permission in the LinkedIn authentication pane, but If I remove `w_share` from my scope, it doesn’t appear in the pane, so I just kept `w_share`.

Eiither way, I always get the same raw array.

**Comment by ockam** [comment]
OK. I now know what is happening.

First, the LinkedIn provider already has default scopes (r_basicprofile and r_emailaddress). Scopes from config are appended so, if you repeat those in the config, they duplicate and the LinkedIn API doesn’t deal with duplicate (you will see permission request twice for each scope that is a duplicate).

Second, the LinkedIn API doesn’t automatically return all possible fields for a scope. You need to specify the ones you need.

Since there is no way to specify the profile fields, I will need to extends the provider, but that would be a nice feature to add.

**Comment by ockam** [comment]
In case someone else hits the same issue, here’s what you need to do.

First, extend EloquentOAuthServiceProvider to register your custom social provider:

```
namespace App\Providers;

use  AdamWathan\EloquentOAuthL5\EloquentOAuthServiceProvider;

class CustomSocialLoginServiceProvider extends EloquentOAuthServiceProvider
{

    protected $providerLookup = [
        'linkedin' => 'App\Providers\AppLinkedInProvider',
    ];
}
```

Then add this provider to your app config providers array instead of the original one.

Finally, extend the LinkedIn provider and add your required fields:

```
namespace App\Providers;

use SocialNorm\LinkedIn\LinkedInProvider;

class AppLinkedInProvider extends LinkedInProvider
{
    /**
     * LinkedIn fields must be specified to be included in the response
     *
     */
    protected $profileFields = array(
        'id',
        'first-name',
        'last-name',
        'email-address',
        'picture-url',
        'headline',
        'location:(name)',
        'public-profile-url',
    );
}
```

**Comment by adamwathan** [comment]
Ah, Facebook made some updates recently that had the same effect. I was thinking of making the fields configurable for that reason and this is another push in that direction...

**Comment by adamwathan** [comment]
Closing because this package is no longer actively maintained; for changes, fixes, or new features, please fork.
