### ISSUE TITLE
Call to undefined method "authorize"

### ISSUE THREAD

**Issue by kschu91** [adamwathan/eloquent-oauth-l5#17]
I always getting the error:

```
    FatalErrorException in routes.php line 19:
    Call to undefined method AdamWathan\EloquentOAuthL5\EloquentOAuthServiceProvider::authorize()
```

app/Http/routes.php

```
<?php
...
Route::get('/github/authorize', function() {
    return SocialAuth::authorize('github');
});
```

config/app.php

```
    'providers' => [
        ...
        AdamWathan\EloquentOAuthL5\EloquentOAuthServiceProvider::class,
    ],

    'aliases' => [
        ...
        'SocialAuth'=> AdamWathan\EloquentOAuthL5\EloquentOAuthServiceProvider::class,
    ],
```

I have done the installation via composer. Executed the installation and migration like described in the manual.

**Comment by kschu91** [comment]
The following works fine. But that´s not the way like in the documentation:

```
$this->app['adamwathan.oauth']->authorize('github')
```

**Comment by adamwathan** [comment]
You have the alias pointing to the wrong class, it should point to the facade, not the service provider. Double check the docs, they are correct :+1: Would paste example but just quickly replying from phone, sorry!
