### ISSUE TITLE
 Class hash does not exist 

### ISSUE THREAD

**Issue by syphernl** [adamwathan/eloquent-oauth-l5#2]
After upgrading to this package rather than the branch in the old project I'm getting this exception. This seems to originate from AuthManager.

**Comment by adamwathan** [comment]
Hmm I can't replicate this, there is no reference to the `Hash` class in either this, or the EloquentOAuth base code base. Are you sure it's related to the package?

**Comment by syphernl** [comment]
It was working fine when I was on the `adamwathan/eloquent-oauth` package (branch `laravel-5`) and this particular exception started when I moved to the `-l5` edition (which seems to differ quite a bit from the `laravel-5` branch)

**Comment by adamwathan** [comment]
Yeah there was a lot of refactoring and extracting of other packages so I totally don't doubt there are hiccups in there somewhere. Can you post the error message? What line in what file is the error?

**Comment by syphernl** [comment]
It seems to cause this issues in Eloquent, since this is where the `$this->app['hash']` is being referred to.

If I check this in the `register()` of my serviceprovider the `hash` binding doesn't exist. If I manually add it like this:

```
        $this->app['hash'] = $this->app->share(function () {
            return new BcryptHasher();
        });
```

it seems to work just fine. Seems like something is preventing Laravel from booting up the hasher.

**Comment by adamwathan** [comment]
That binding is normally registered by Laravel here:

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Application.php#L1036

Can you post the error related to the package?

**Comment by syphernl** [comment]
I'm having some trouble drilling down in the exceptions. A lot of Laravel internal stuff is going on which I have no idea what it does/should do, but it appears that this may be a issue unrelated to this package.
