### ISSUE TITLE
Don't allow soft-deleted users to login

### ISSUE THREAD

**Issue by lextoc** [adamwathan/eloquent-oauth-l5#22]
I'm using your package in my app and I'm also using laravel's soft delete (http://laravel.com/docs/5.1/eloquent#deleting-models). 

When a soft-deleted user tries to login there's an error:
`No query results for model [App\User].`

I tried intercepting it with a little bit of code you posted in another issue:

``` php
$existing_user = User::where('email', $details->raw()['email'])->first();

if ($existing_user !== null && is_null($existing_user->deleted_at) == false) {
    return view('banned');
}
```

But that doesn't work because even if I add an else to the if statement and return another view it will still give the error. I am quite of a newbie so apologies if this isn't a real issue, just figured posting wouldn't hurt.

Besides this little encounter I've had no problems with your package, good job!

**Comment by adamwathan** [comment]
Ah yeah, you probably want to make sure you delete the record in the `oauth_identities` table that maps to the use after you soft delete them :/ I'm sure I can make this easier, will see what I can do.

**Comment by lextoc** [comment]
I'm using soft delete to sort of ban (and unban) users. I believe that if I delete the record in `oauth_identities` I can't track the user back and he will be able to create a new account and log in again.

I will use a banned field in my `users` table for now :)

Thanks for the reply.

**Comment by adamwathan** [comment]
Closing because this package is no longer actively maintained; for changes, fixes, or new features, please fork.

**Comment by lequy1010** [comment]
@lextoc
You should override method login of AuthenticatesUsers
In Auth\LoginController you add a function login as below

```
public function login(Request $request)
    {
        if(Auth::attempt([
            'email' => $request->get('email'),
            'password' => $request->get('password')
        ])){
           // Login success and get user's info to check
            if (\auth()->user()->deleted_at != null){
               // Put your code in case use has been soft deleted
             }
        } else {
           // Login fail
   }
```
