### ISSUE TITLE
Object of class GuzzleHttp\Psr7\Response could not be converted to string

### ISSUE THREAD

**Issue by suvarnap** [adamwathan/eloquent-oauth-l5#23]
@adamwathan 
Currently i am using your package for logging to soundcloud but facing above issue when call
SocialAuth::login('soundcloud');
Its working for google, github etc.

**Comment by adamwathan** [comment]
Ah thanks for catching this, SoundCloud seems to have tightened up their API a bit and I was missing a header. Tagged a new version of the SoundCloud provider here: https://github.com/adamwathan/socialnorm-soundcloud/releases/tag/v0.2.2

You should be able to just `composer update` and have things work now. Let me know if it's all good so I can close the issue!

**Comment by suvarnap** [comment]
@adamwathan 
Thanks!
Now its working properly.
