### ISSUE TITLE
ApplicationRejectedException in Request.php

### ISSUE THREAD

**Issue by suvarnap** [adamwathan/eloquent-oauth-l5#24]
@adamwathan 
I have logout through my application normally or without login cancel from soundcloud
i am getting issue ApplicationRejectedException.
in query string => ?error=access_denied&error_description=The+end-user+denied+the+request.?error=access_denied&error_description=The+end-user+denied+the+request.

**Comment by adamwathan** [comment]
Still having trouble with this or did you manage to figure it out? Seems to be working ok over here, is the project open source by any chance?

**Comment by suvarnap** [comment]
It's working now.
