### ISSUE TITLE
Error  "Object of class GuzzleHttp\Psr7\Response could not be converted to string" when InvalidAuthorizationCode exception thrown in socialnorm

### ISSUE THREAD

**Issue by jpalala** [adamwathan/eloquent-oauth-l5#25]
I'm facing the same issue #23, this time with Google login, and Laravel 5.2 . 

Screenshot here: https://www.dropbox.com/s/iw0yxhpvcy097dd/2015-12-05%2011_54_17-mentorsdojo.com_google_login_state%3Dg4uQsWej5Mvna17jRyjwLxtsdfKN9CeO%26code%3D4_HbUE0.png?dl=0

**Comment by adamwathan** [comment]
@jpalala try doing a `composer update` and make sure it pulls in v0.2.2 of SocialNorm. It might not fix the issue but will hopefully give more information.

I fixed an issue here that would give you that error if an `InvalidAuthorizationCode` exception was thrown,  but had forgot to tag a release: 
https://github.com/adamwathan/socialnorm/commit/c99860a8ab338481c8db30d6d080cd1f4b1352cd

**Comment by jpalala** [comment]
Cool thanks. It started working again after I updated/fixed my google auth tokens by making sure I had the right redirect url, paired with the right google client id and key :)
