### ISSUE TITLE
Laravel 5.2 PHP Artisan Command Line Failure

### ISSUE THREAD

**Issue by Close0** [adamwathan/eloquent-oauth-l5#27]
So I was following the guide on how to setup Laravel 5 with your OAuth library.

However it seems that once I added 'AdamWathan\EloquentOAuthL5\EloquentOAuthServiceProvider' to my providers app config I was no longer able to run the php artisan command. I would be met with this error:
vagrant@homestead:~/Code/Laravel/upkeep$ php artisan
  [ReflectionException]
  Class Illuminate\Foundation\Composer does not exist
vagrant@homestead:~/Code/Laravel/upkeep$

I then dug down to the InstallCommand file and changed
use Illuminate\Foundation\Composer; to use Illuminate\Support\Composer;

I was then able to continue with the install process. :+1: 

_Ninja edit_
Welp. I think quite a lot changed with 5.2. I used php artisan make:auth to start with all the controllers / views. There appears to be big changes from the Laravel 5 repo you have uploaded (from what I can tell, this is actually my first Laravel project ever).

**Comment by adamwathan** [comment]
Ah thanks for the heads up, looks like some stuff moved for 5.2 :/ Will have to see if I can think of a clever way to support 5.1 and 5.2 in the same package.
