### ISSUE TITLE
Facade/exceptions in readme

### ISSUE THREAD

**Issue by syphernl** [adamwathan/eloquent-oauth-l5#3]
According to the readme, the facade (and exceptions) point to the `eloquent-oauth` project rather than `eloquent-oauth-l5`.

**Comment by adamwathan** [comment]
Yeah this is correct, this package uses that package under the hood. I just pulled out the installation/service provider related stuff into separate Laravel 4 and Laravel 5 packages, but kept all of the base logic in the main package. Seemed like the easiest way to support both Laravel versions :+1:
