### ISSUE TITLE
Laravel 5.2 and Illuminate\Foundation\Composer vs Illuminate\Support\Composer

### ISSUE THREAD

**Issue by mhluzi** [adamwathan/eloquent-oauth-l5#34]
Hi Adam

Just fyi, and maybe this is catered for already somewhere else but have just upgraded a site to Laravel 5.2 and had to change a line in:

vendor\adamwathan\eloquent-oauth-l5\src\Installation\InstallCommand.php

changed:
use Illuminate\Foundation\Composer
to
use Illuminate\Support\Composer;

Hope that helps someone!

Cheers
m

**Comment by adamwathan** [comment]
Hey @mhluzi! This was actually fixed in 0.4.1, using some gnarly-ass version detection :+1: 

https://github.com/adamwathan/eloquent-oauth-l5/blob/master/src/Installation/InstallCommand.php#L21-L25

**Comment by mhluzi** [comment]
Legend. .thanks!
