### ISSUE TITLE
Not storing profile information (Facebook Provider)

### ISSUE THREAD

**Issue by wilcho-vnz** [adamwathan/eloquent-oauth-l5#35]
Hello Adam, 

After the app authorization the callback URL(http://localhost:8000/facebook/login) the app does not store the user data of Facebook.
I followed all steps of your example in how to use Eloquent OAuth service provider, but I cannot see the problem.

Maybe is an update on Facebook that broke your code.

Greetings

**Comment by adamwathan** [comment]
Can you show me your code? It won't save Facebook profile data automatically, you need to save the data you want to keep however your data is structured.

For example, this call will create a user and associate them with the Facebook account they logged in as, but it won't save any Facebook data, like their username, email, profile photo, etc.

```
SocialAuth::login('facebook')
```

This on the other hand will save the full name and email returned from Facebook:

```
SocialAuth::login('facebook', function ($user, $details) {
    $user->name = $details->full_name;
    $user->email = $details->email;
});
```

It's up to you to store that data if you need it, by doing whatever you want with it in that closure.

I just tested the latest versions of everything locally and not seeing any issues here.

**Comment by wilcho-vnz** [comment]
Hi Adam,  

This is the Route that does not works

```
Route::get('facebook/login', function() {
    try {
        SocialAuth::login('facebook', function($user, $details) { // this line does not works to get the user data to store it in the database
          $user->nickname = $details->nickname;
          $user->name = $details->full_name;
          $user->profile_image = $details->avatar;
          $user->save();
        });
    } catch (ApplicationRejectedException $e) {
        // User rejected application
    } catch (InvalidAuthorizationCodeException $e) {
        // Authorization was attempted with invalid
        // code,likely forgery attempt
    }

    // Current user is now available via Auth facade
    $user = Auth::user();

    return Redirect::intended();
});
```

Develop on my localhost does affect the flow of the authentication?

Thanks for your reply

**Comment by adamwathan** [comment]
Are you seeing an error at all, or is the data just not saving? What happens when you `dd($details)` in the closure?

**Comment by wilcho-vnz** [comment]
I get this error
Undefined variable: details

This is what I receive on my route after the facebook auth:

`http://localhost:8000/facebook/login?code=AQCfDCRs7Q_3pEBLAzNkhx7OWZtilnbKObQ5JhFG-IoHO7CpwqIa8e5aWevlEFOeSmpCgHKw77kJHGZTl0zd9lRtO7cczZeNdreGOqCUlmPG53KK2OF-4ygLsXzLCtdOTSf7jtjopklFwv-7TGTSwLDO6Sn1L4Yypde3UHOCNgPY-30RtmOseB7gz6g22ppoMV2Gh5oF43I1VWsI5VpLU3PmJpNKscbphmFmZ09bYDP0jeeskRnHVxBpaOgcsDAdwOpwgKuFYLAm5lv82DAP6DGRZ5OamgbIIxbT5N29ixEhcJy2FHIio7HHC9__YIDDLyu1CghPNfeYu6qk_wnwxj5j&state=5pg1fQfAYUjIbwDVS1vQb8XOxLXkHXZL#_=_`

**Comment by adamwathan** [comment]
And that is being triggered when you call `$details->nickname` inside the closure? Super unusual... Any chance you can do `dd(func_get_args())` inside the closure and post the results?

**Comment by wilcho-vnz** [comment]
No, no, no.
That chain is the URL that returns Facebook ti my browser after authorize the app.
dd($details->nickname) returns: Undefined variable: details

**Comment by adamwathan** [comment]
No I meant the error is happening in the closure. Can you try the func_get_args thing I was talking about?

```
Route::get('facebook/login', function() {
    try {
        SocialAuth::login('facebook', function($user, $details) {
          dd(func_get_args());
          $user->nickname = $details->nickname;
          $user->name = $details->full_name;
          $user->profile_image = $details->avatar;
          $user->save();
        });
    } catch (ApplicationRejectedException $e) {
        // User rejected application
    } catch (InvalidAuthorizationCodeException $e) {
        // Authorization was attempted with invalid
        // code,likely forgery attempt
    }

    // Current user is now available via Auth facade
    $user = Auth::user();

    return Redirect::intended();
});
```

**Comment by wilcho-vnz** [comment]
SocialAuth::login('facebook', function($user, $details) does not execute, so I can't see what dd(func_get_args()) print
Maybe I am missing something configuring the Facebook app

**Comment by adamwathan** [comment]
Any chance you can share the file that the error is occurring in and the exact error message? I don't understand how you were getting "Undefined variable $details" if the closure was never executing.

**Comment by twisctid** [comment]
I'm having the EXACT same problem. after facebook redirects nothing happens

EDIT
well actually. its really throwing an InvalidAuthorizationCodeException. Perhaps that's what's happening to you as well wilcho-vnz

**Comment by wilcho-vnz** [comment]
But, you get an error(InvalidAuthorizationCodeException) and your app dies or Facebook redirect to your callback URL configured in your Facebook App after the authorization but with no data?

**Comment by adamwathan** [comment]
What error are you seeing and on what line? Can you share something
reproducible? Open source a small example app that demonstrates the problem
maybe? Would really help me out in either fixing the bug or helping you
with something you are doing incorrectly.

**Comment by twisctid** [comment]
i removed the try catch to see what was happening and thats what i got. so the facebook redirect works and the method is executed but it throws the error.... not sure if its due to absent data .

i'm using a clean install of Laravel 5.2, this is the only module added so far.

i attached the error page and here are the routes

Route::get('facebook/authorize', function() {
    return SocialAuth::authorize('facebook');
});

Route::get('facebook/login', function() {

```
SocialAuth::login('facebook');

// Current user is now available via Auth facade
$user = Auth::user();

return Redirect::intended();
```

});

i know my fb config is legit because i used the exact same fb app on a previous version of my site built on drupal

if it comes to it i'll open source an app in the morning to demonstrate

[error.html.zip](https://github.com/adamwathan/eloquent-oauth-l5/files/168423/error.html.zip)

**Comment by adamwathan** [comment]
@twisctid Make sure your routes are defined inside the `web` group to ensure sessions are enabled. Can you post your routes file and any relevant controllers?

**Comment by twisctid** [comment]
my controllers only return views. no extra code in any of them
[routes.php.zip](https://github.com/adamwathan/eloquent-oauth-l5/files/168430/routes.php.zip)

**Comment by twisctid** [comment]
I just verified that facebook is indeed returning data by putting dd($details) inside my closure
UPDATE
making progress. not only is fb returning data but the module is creating the user and associating it. still no session though. i'll continue to investigate
UPDATE
solved
as it turns out i have to use a closer for it to retrieve anything. secondly need to ensure the sessions folder is writeable, thirdly ALL the routes should be in the web group for auth to work
