### ISSUE TITLE
Weird Login Issue - Existing user migrated from google apps

### ISSUE THREAD

**Issue by jaydombroski** [adamwathan/eloquent-oauth-l5#37]
First off, great add-on! It's been working very well up until I moved a domain from one google apps account to a new one. Basically, the domain was a add-on one original google app, not it's a stand alone on it's own google app. 

That being said, when a user goes to sign in, they keep getting the following error thrown:

`No query results for model [App\User].` 

At this point, I was able to get some users logged in by doing the following: 
1. User logs into app.
2. A null user is then created.
3. Remap oauth_identities empty row to existing user (change user_id)
4. User signs back in, and has access

Not the prettiest, but seems to work. Of course the last user is not following this process and I cannot get a empty user created, or have them log in.

We are only using Google+ Oauth. I have revoked permission at Google Apps, that did not work. I have deleted the user and his oauth_identities row, I have deleted all session files, cleared cache, and he still cannot log in I'm at wits end. Here is my Auth code:

`
     public function handleProviderCallback($provider)
       {
           try {
              SocialAuth::login('google',function($user, $details){

```
            //check to see if the user has a team email.
            //if($this->teamCheck($details->raw()['email']) == false){
              //  throw new Exception;
            //}

            //explode full name from google
            $name = explode(" ", $details->raw()['name']);

            //check to see if user exists.
            try {
                $userExists = User::where('email', '=', $details->raw()['email'])->first();
            }
            catch(Exception $e){
                dd($e);
            }

            //Very ugly code to save users. Needs to be refactored
            if(!is_null($userExists)){
                $userExists->email        = $details->raw()['email'];
                $userExists->first_name   = $name[0];
                $userExists->last_name    = $name[1];
                $userExists->avatar       = $details->raw()['picture'];
                try{
                    $userExists->save();
                }
                catch(Exception $e){
                    dd($e);
                }
            }
            else{
                $user->email              = $details->raw()['email'];
                $user->first_name         = $name[0];
                $user->last_name          = $name[1];
                $user->roles              = 'N';
                $user->avatar             = $details->raw()['picture'];
                try{
                    $user->save();
                }
                catch(Exception $e){
                    dd($e);
                }
            }

            //check for admin
            if( env('ADMIN_EMAIL') == $details->raw()['email'] ){
                session()->put('is_admin', true);
            }

        });
    } catch (ApplicationRejectedException $e) {
        // User rejected application
    } catch (InvalidAuthorizationCodeException $e) {
        // Authorization was attempted with invalid
        // code,likely forgery attempt
    }
    catch(Exception $e){
        return redirect('auth/login');
    }
```

`

Odd note, when on my local instance, I was able to create the user and log in with no problem.

Thanks,

Jay

**Comment by kingbri90z** [comment]
@jaydombroski I recall this happening when the user is not found in the User model. However, the code is seeing the user as an existing user from what is inside eloquent-oauth. Depending on your concerns, you could force every user to re-register by truncating the eloquent-oauth table. 
Maybe @adamwathan has a better suggestion.

**Comment by adamwathan** [comment]
Closing because this package is no longer actively maintained; for changes, fixes, or new features, please fork.
