### ISSUE TITLE
Problem with user has same email address on login

### ISSUE THREAD

**Issue by odera89** [adamwathan/eloquent-oauth-l5#38]
When the user has same email address ex. on facebook or on gmail account, and in the database the email address it's set unique, and the email address exists in DB the login not working correctly. 
Gets an error, "Duplicate entry..." because the user already exists..
Any solution?

**Comment by adamwathan** [comment]
Hey @odera89, in this case it's really up to you to decide what makes sense for your app. Do you want to allow two accounts to exist that have the same email? If so just remove the unique constraint.

If you don't want to allow someone to sign up with Facebook if someone else has signed up using Google using an account that provides the same email, you can catch the exception and display some sort of message to the user.

If you want to merge the accounts, there's some information here: https://github.com/adamwathan/eloquent-oauth-l5/issues/10#issuecomment-172864961

Note that there are security implications to doing that automatically though, so read the whole thread. Cheers!
