### ISSUE TITLE
EloquentOAuthServiceProvider not found

### ISSUE THREAD

**Issue by thepeels** [adamwathan/eloquent-oauth-l5#41]
Hi, I have successfully implemented eloquent-oauth-l4 on my local machine.
My production server is on a shared host with PHP5.4.37, and so after some false trails, I have managed to install V0.1.2 (before support for PHP5.4 was withdrawn)
I now get this error when I try to 'php artisan dump-autoload' -

{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'AdamWathan\EloquentOA
uthL4\EloquentOAuthServiceProvider' not found","file":"\/home\/jc\/vendor\/laravel\/framework\/src\/Illuminate\/Foun
dation\/ProviderRepository.php","line":157}}

Have you any ideas to help?

**Comment by thepeels** [comment]
Further, this particular error disappears if I comment out the new lines on the providers array and the alias array in config/app. But then of course I get Class Oauth not found.
I have got no mention of AdamWathan in the vendor/composer/autoload_classmap.php

**Comment by thepeels** [comment]
I have got no mention of AdamWathan in the vendor/composer/autoload_classmap.php

**Comment by thepeels** [comment]
Ok, I sorted it now, I had a line in the composer.json classmap array which composer could not resolve, locally it didn't matter, but on the production site, it was causing composer to fail to finish the job. (not well indicated by the error message). Now everything works as it is supposed to, Thanks for reading if anybody did :-)

**Comment by adamwathan** [comment]
Glad it's sorted! Have been reading along but on an island for honey moon
so not able to help much :)
