### ISSUE TITLE
cannot get gender from facebook

### ISSUE THREAD

**Issue by sonill** [adamwathan/eloquent-oauth-l5#42]
facebook login is working but cannot get gender.
I am using this code
`SocialAuth::login('facebook', function($user, $details) {
        dd( $details->raw()['gender'] );
});`

Appreciate your help

**Comment by chrissy-dev** [comment]
@sonill I couldn't get locale either ... :(

**Comment by danhunsaker** [comment]
Don't forget to add any additional scope(s) you need to actually retrieve the information you're interested in.

**Comment by adamwathan** [comment]
Closing because this package is no longer actively maintained; for changes, fixes, or new features, please fork.
