### ISSUE TITLE
Exception: Publish package configuration in Laravel 5.2

### ISSUE THREAD

**Issue by tejasshah93** [adamwathan/eloquent-oauth-l5#43]
As in mentioned in #11 , I'm also facing the same issue while publishing the package configuration (after installing package, adding provider and facade)
On running `php artisan eloquent-oauth:install`, it gives the following error:

```
[Symfony\Component\Console\Exception\CommandNotFoundException]
There are no commands defined in the "eloquent-oauth" namespace.
```

Also tried with: `php artisan vendor:publish --provider="AdamWathan\EloquentOAuthL5\EloquentOAuthServiceProvider"`
which responds: `Nothing to publish for tag []`.
Am I missing something here?

P.S. I'm new to Laravel

**Comment by adamwathan** [comment]
Sounds like you haven't registered the provider properly in `config/app.php`. Make sure your `config/app.php` file looks like this (double check the namespace import):

``` php
<?php

use AdamWathan\EloquentOAuthL5\EloquentOAuthServiceProvider;

return [
    // ...
    'providers' => [
        //  ...
        EloquentOAuthServiceProvider::class,
    ],
    // ...
];
```
