### ISSUE TITLE
API calls from the server require an appsecret_proof 

### ISSUE THREAD

**Issue by topsub** [adamwathan/eloquent-oauth-l5#46]
This is the error i get when i get redirected back to my app.

The redirect to facebook to approve the works perfect, but when i get redirected back to my website this gets spit out at me:

`Client error:`GET https://graph.facebook.com/v2.4/me?access_token=EAAQalYXTmbsBAG1YokHVgUZCW6n0qwt7QKnd6D3ZAKgaJhRilpbHXmFhFgot4PvC16vABO2KU7X4pjp5vxWLjNPkJH5iogt8M5JicJ5QGHCZBHdSUGw7j9ZAQda8fG9jhZB4lY193hMMAh7zrx02FoMhmvum0GwoZD&fields=email,name,first_name,last_name,age_range,timezone` resulted in a `400 Bad Request` response:
{"error":{"message":"API calls from the server require an appsecret_proof argument","type":"GraphMethodException","code" (truncated...)`

What am i missing?

**Comment by adamwathan** [comment]
Closing because this package is no longer actively maintained; for changes, fixes, or new features, please fork.
