### ISSUE TITLE
Why are you using another config file?

### ISSUE THREAD

**Issue by kevinruscoe** [adamwathan/eloquent-oauth-l5#47]
Laravel ships with a services.php config that house an array of 3rd party, why not rely on that one in stead of the providers.php one?

**Comment by adamwathan** [comment]
The documentation suggests publishing your own package configuration, and `services.php` wasn't a thing when this package was originally released:

https://laravel.com/docs/5.3/packages#configuration

I'd rather publish the config file for people to modify vs. having them copy and paste from the documentation.
