### ISSUE TITLE
Nice package but can be framework agnostic. Can you do that please

### ISSUE THREAD

**Issue by drnkwati** [adamwathan/eloquent-oauth-l5#48]
Hi. I love this package but it is too tied to Laravel framework. When i look at the package dependencies i think we can move the following illuminate packages to their laravel spercific implimentation:
illuminate/auth, illuminate/session, illuminate/http and illuminate/routing. You can leave illuminate/database and illuminate/support in the main package. that way we can adapt the package in other frameworks like Slim.
thanks

**Comment by adamwathan** [comment]
This _is_ the Laravel 5 specific implementation, hence L5 in the name.

It's built using:

https://github.com/adamwathan/eloquent-oauth

...which is built using these 7 packages, none of which are tied to Laravel:

https://github.com/search?q=user%3Aadamwathan+Socialnorm

You can reimplement the framework specific functionality on top of those.
