### ISSUE TITLE
OAuth Facade Conflict?

### ISSUE THREAD

**Issue by cillosis** [adamwathan/eloquent-oauth-l5#5]
I followed the instructions exactly for installation of this package and used your route based setup from the video for the authorize and login resources, but I consistently get the following error:

> Call to undefined method OAuth::authorize()

Being inside of the **routes.php** file, I am not inside of a namespace, although I also tried `\OAuth::authorize()` as well. This is the relevant section of my route file:

```
Route::get('google/authorize', function() {
    return OAuth::authorize('google');
});
Route::get('google/login', function() {
    return OAuth::login('google', function ($user, $details) {
        dd($details);
    });
});
```

After banging my head for a bit, I tried renaming the facade alias in **app.php** to `OAuth2` and changed  my calls to use that instead, _and it worked just fine_.

I've confirmed that I do not have any other classes in my project or vendor folder with that same name. Doing a global grep of my project shows that the only class with that name is the facade itself (_adamwathan/eloquent-oauth/src/Facades/OAuth.php_), but it is namespaced so shouldn't cause a conflict and I don't have anything else with that name listed in my **app.php** aliases.

I also just tried upgrading my project to 5.1 since it was just released and have the same issue.

And of course, I have run `composer du` until I am blue in the face just to be sure ;-)

Have you run into this? If so, do you know what would be causing something like that? I can leave my alias as something else, but it would be nice if I could get it to work as intended.

**Comment by adamwathan** [comment]
Super bizarre, try `dd(OAuth::class)` and see what the underlying class is?

**Comment by cillosis** [comment]
Sorry for the delay. 

```
dd(OAuth::class);
```

Comes back as "_OAuth_". Although, I tested trying to use that magic constant on arbitrary class names like `dd(NonexistantClass::class);` and it comes back as "_NonexistantClass_" so I am not sure how useful that is.

In your service provider (**EloquentOAuthServiceProvider**), I tried doing `dd($this->app['adamwathan.oauth']);` at the end of the `registerOAuthManager()` function and it throws an error about the Reflection class not being able to resolve "hash". It was basically the same issue as this closed ticket: https://github.com/adamwathan/eloquent-oauth-l5/issues/2

I've spent the last hour and half trying to get to the bottom of it and quite frankly, I have no idea. It might be a symptom of upgrading from 5.0 to 5.1 and the Laravel guide missing something. I've already found a  couple weird issues that weren't part of the upgrade docs.

Anyway, great library and if I find something I can do to give back, I will!

**Comment by adamwathan** [comment]
Hmm weird! Can you by any chance create a minimal Laravel project replicating the issue and throw it up publicly?

**Comment by cillosis** [comment]
I created a brand new Laravel 5.1 app and copied over a little bit of my (small) app logic and re-setup this package. Same issue. But, I think I've narrowed something down. When I do this:

``` php
Route::get('{provider}/authorize', function($provider) {
    return OAuth::authorize($provider);
});
```

I get:

![image](https://cloud.githubusercontent.com/assets/1303759/8361823/4be0f96c-1b43-11e5-8d9c-92464c45ae9a.png)

But, curiously, when I get the service directly, it works fine:

``` php
Route::get('{provider}/authorize', function($provider) {
    return $this->app['adamwathan.oauth']->authorize($provider);
});
```

So, for some reason it REALLY does not like the `OAuth` name. I've grep'ed my entire project folder including vendors looking for any conflicts and cannot find any. Also, like I said, if I change the facade alias in config/app.php to something like `OAuthSomething` it will work fine as well.

I will see about throwing together a fresh dummy install to reproduce the issue.

**Comment by cillosis** [comment]
Ok Adam, I created a new project and loaded the package in. I didn't even have to bother with setting up the database or config settings or anything like that because it never gets that far. I only added the service provider and alias to the app.php config. In the routes file, I did this:

``` php
Route::get('/', function () {
    return OAuth::authorize('facebook');
});
```

And the result is the error from before:

> Call to undefined method OAuth::authorize()

https://github.com/cillosis/eloquent-oauth-l5-issue

**Comment by adamwathan** [comment]
I just cloned that repo, ran composer install, generated an app key and got this error :(

![image](https://cloud.githubusercontent.com/assets/4323180/8362637/0eda70b6-1b48-11e5-9aa1-3e15fd3ecdc8.png)

Are you using Homestead? This was just running it using the built in PHP server under OSX.

**Comment by cillosis** [comment]
OMG. I think I know why it is doing this. Take a look at this:

http://php.net/manual/en/book.oauth.php

When I tried `dd(get_class_methods('OAuth'))` it came back with a whole list of methods. I googled some of them and came up with that extension. So, it seems the conflict is not necessarily the package, nor an issue with Laravel, it is global.

For me, doing this `dd(extension_loaded('OAuth'));` comes back `true`. 

Phew. That took entirely too long to figure out. Might want to either suggest a different name for the facade in the documentation or add a check using `extension_loaded()` to detect if that is loaded and throw an exception.

**Comment by adamwathan** [comment]
Ah man that is lame! Ok, I will rename the facade for the next version. It was a shitty name anyways. Thanks for your help!

**Comment by cillosis** [comment]
No, not using homestead -- probably should. I'm just running an install on MacOS from http://php-osx.liip.ch.

**Comment by cillosis** [comment]
Sure man, no problem. Other than that, its super easy to use. Thanks for making this!

**Comment by tankerkiller125** [comment]
A temp fix would be to disable the PHP-Oauth plugin (since its Oauth 1.0 and should be depreciated anyways) of course this does pose a problem for shared hosted sites.

**Comment by bsheikh** [comment]
Thats weird, I've encountered the same problem. How did you manage to fix it @cillosis ?

**Comment by adamwathan** [comment]
@tankerkiller125 Just alias it as something else in your `config/app.php`:

``` php
'aliases' => [
    // ...
    'SocialAuth' => 'AdamWathan\EloquentOAuth\Facades\OAuth',
    // ...
]
```

Or don't alias it at all, and instead import the full `use AdamWathan\EloquentOAuth\Facades\OAuth` in the classes that need it.

**Comment by skyrpex** [comment]
SocialAuth looks like a better name than eloquent oauth for this package. Just saying... :+1:

**Comment by cillosis** [comment]
That is what I ended up using.

**Comment by adamwathan** [comment]
@skyrpex Agree, maybe will change down the road...

**Comment by adamwathan** [comment]
I've updated the installation instructions to use `SocialAuth` as the facade reference, thankfully doesn't involve changing any code :)

https://github.com/adamwathan/eloquent-oauth-l5/releases/tag/v0.3.1

**Comment by MuhammadFaisalA** [comment]
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method AdamWathan\EloquentOAuth\Facades\OAuth::isDeferred()
