### ISSUE TITLE
Installation Problem 

### ISSUE THREAD

**Issue by abunour22** [adamwathan/eloquent-oauth-l5#50]
Problem 1
    - Installation request for adamwathan/eloquent-oauth-l5 ^0.5.1 -> satisfiable by adamwathan/eloquent-oauth-l5[v0.5.1].
    - adamwathan/eloquent-oauth-l5 v0.5.1 requires guzzlehttp/guzzle ^6.2.1 -> satisfiable by guzzlehttp/guzzle[6.2.1, 6.2.2, 6.2.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by adamwathan** [comment]
Sounds like you have a different version of Guzzle already installed, do
any of your other dependencies require Guzzle?

One thing to try that sometimes works is just deleting the vendor directory
and the lock file and rerunning composer install.
