### ISSUE TITLE
Sentinel integration

### ISSUE THREAD

**Issue by tachyon-ops** [adamwathan/eloquent-oauth-l5#52]
Hi there
I come to you because I really wanted to use a free option for social logins with sentinel. So, if you do find interesting to proceed with this work, I can start up by giving you my current error message (bacause I'm trying to insert a Sentinel User model in eloquent-oauth.php conf:

`ErrorException in SessionGuard.php line 441: Argument 1 passed to Illuminate\Auth\SessionGuard::login() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of Modules\User\Entities\Sentinel\User given, called in vendor/adamwathan/eloquent-oauth/src/Authenticator.php on line 21 and defined`

@adamwathan  Can you guide me?

**Comment by adamwathan** [comment]
I've never worked with Sentinel so no idea if the two packages would be compatible. It sounds like the mismatch is between Laravel's SessionGuard and Sentinel though, so if those aren't compatible, this package won't work with Sentinel either.

**Comment by tachyon-ops** [comment]
Thanks @adamwathan 

I had to find another way to go about it. Perhaps you could leave the 'login' to be made manually if asked and just create a way to grab the content from the encripted strings? I'm using socialite to give me that:
$socialUser = Socialite::driver('google')->user();

Then I go about my way with Sentinel.
