### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by quinxy** [adamwathan/eloquent-oauth-l5#53]
I don't have much information to relate.  I followed the video guide and the github instructions.  But when I add a route such as:

Route::get('{provider}/authorize', function ($provider) {
	return OAuth::authorize($provider);
});

And try to go to it I get Error 500.  I have logging enabled but nothing shows up in the logs or on screen.  I tried adding custom exception handler to display more info but that didn't seem to work.

I added debug code inside SocialNorm.php authorize() to see if it was at least being called (since I think that's what the route is ultimately calling) but the line is never reached.  All other code on the site works.

Any ideas?  Not sure if I'm doing something very stupid or it's some issue with the eloquent-oauth-l5 and maybe Laravel 5.3.

**Comment by vmitchell85** [comment]
@quinxy are you still getting this error? Does it show up when you add the route or when you hit the route after adding it?

**Comment by quinxy** [comment]
Sorry, I ended up switching to another library, so I don't know.
