### ISSUE TITLE
Tag for Laravel 5.4-support?

### ISSUE THREAD

**Issue by nickurt** [adamwathan/eloquent-oauth-l5#54]
Is it possible to tag the latest commit (share -> singleton), then it's possible that I can use the latest tag instead of dev-master commit.

**Comment by adamwathan** [comment]
I haven't actually had time to test it's working properly with 5.4 yet but pushed that commit to help someone in a bind, haha...

Have you tried dev-master, working good?

**Comment by nickurt** [comment]
Yes, it works fine with 5.4 :)

**Comment by adamwathan** [comment]
Done!
