### ISSUE TITLE
Allow more than one scope

### ISSUE THREAD

**Issue by m1guelpf** [adamwathan/eloquent-oauth-l5#55]
It'd be awesome if you could pass the scope needed to the authenticate function.
I've looked at the code, but I haven't been able to find the place where the scope is passed to the github provider.
Could you point me in the rigth direction?

**Comment by adamwathan** [comment]
You can provide as many scopes as you like in an array in the config file:

https://github.com/adamwathan/eloquent-oauth-l5/blob/master/config/eloquent-oauth.php#L25

Here's the actual code where the scopes get applied to the provider:

https://github.com/adamwathan/socialnorm/blob/master/src/Providers/OAuth2Provider.php#L37-L39

Cheers!

**Comment by m1guelpf** [comment]
@adamwathan Is there any way I could tweak the authorize method to get the scope as a parameter?

**Comment by adamwathan** [comment]
Any reason why you need the scope in the authorize method? It should be static for the whole app, not dynamically changing or anything. You can get any additional scopes that have been configured using Laravel's `config` helper, and merge those with the default scopes that are there permanently and specified in the GitHubProvider class.

**Comment by m1guelpf** [comment]
@adamwathan And what if I want to get only the user data in certain part of my app and get user repos in another? There should be a better option to do that...

**Comment by adamwathan** [comment]
You would need to configure two different GitHubProviders if you really want to make sure one access token has no access to repos, so you're probably going to need to do a lot more custom work anyways.

Does your app actually have 2 completely discrete OAuth flows, one that asks for one set of GitHub permissions, and another that asks for different GitHub permissions? That seems unusual to me if so.

**Comment by adamwathan** [comment]
Here's a snippet of my config from a project that does GitHub auth and needs repo access:

```php
<?php
return [
    'table' => 'oauth_identities',
    'providers' => [
        'github' => [
            'client_id' => env('GITHUB_CLIENT_ID'),
            'client_secret' => env('GITHUB_CLIENT_SECRET'),
            'redirect_uri' => env('GITHUB_REDIRECT'),
            'scope' => ['repo'],
        ],
    ],
];
```

I make sure to ask for that permission from the beginning, not as a separate flow later on.

**Comment by m1guelpf** [comment]
@adamwathan I need user data in one place and organization admin access in another, and users that have given the first permission will be promted for new permissions

**Comment by adamwathan** [comment]
I would use totally separate controllers for the two actions so that you already know which scopes would have been requested in each. You'll still have to manually configure two different GitHubProviders with the separate scopes.

**Comment by m1guelpf** [comment]
@adamwathan So, there isn't any easy way to do this?

**Comment by adamwathan** [comment]
Unfortunately not, I don't think this package is the right tool for that job. It's only goal is to make it super simple to create/login users from social networks. If you need anything more sophisticated than that you are better off working with the GitHub API directly.

**Comment by m1guelpf** [comment]
@adamwathan Is easy to migrate from eloquent-oauth to Socialite?
 Does Socialite provide a GitHub integration!

**Comment by adamwathan** [comment]
I don't know, I haven't done it. Socialite provides a lot less out of the box, you have to write all of the user creation/authentication code yourself. If you are doing that and only need GitHub support, you might as well just use Guzzle or similar and write your own classes that interact with the GitHub API.

Here is all of the GitHub-related code for eloquent-oauth:

https://github.com/adamwathan/socialnorm-github/blob/master/src/GitHubProvider.php

Your use case is pretty unusual/unique, so you should expect to need to write a lot of the code yourself.
