### ISSUE TITLE
Is There a way to auth sending email and password to Facebook or google? 

### ISSUE THREAD

**Issue by Jatapiaro** [adamwathan/eloquent-oauth-l5#56]
We have a database with emails of admins, so, we made a separate login page for them that validates if the email provided matchs with one in the table admins. Having the email and password, can we send them to one of the providers for authentication?

**Comment by Gummibeer** [comment]
No. That's 100% against what OAuth is.

**Comment by Gummibeer** [comment]
You can save the linked Facebook-ID in your Database and compare the email from an oauth service with your database. But there is, for good reasons, no way to login to an oauth service by email & password from third party app.

**Comment by Jatapiaro** [comment]
@gummibeer Yeah, thanks for the support. There was a confusion with the requirements.
