### ISSUE TITLE
login in with a customised guard

### ISSUE THREAD

**Issue by rheedwahn** [adamwathan/eloquent-oauth-l5#58]
Please Adam, I am trying to authenticate a custom guard, and its not login in, instead redirecting me to the login route. I have another guard called admin and I am trying to use it with that

like doing something like SocialAuth::guard('admin')->login('facebook');

**Comment by adamwathan** [comment]
Sorry this package is no longer maintained, if you'd like to add support for multiple guards I recommend forking the package for your own needs.

Thanks!
