### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by jerauf** [adamwathan/eloquent-oauth-l5#6]
I'm getting an error that eloquent-oauth-l5 doesn't recommend installing Laravel 5.1. Isn't this package compatible?

**Comment by adamwathan** [comment]
Can you paste the full error? There is nothing in the dependencies that should cause an issue with 5.1, it depends on `4.*|5.*`

**Comment by jerauf** [comment]
I tried re-installing and didn't get the error.

But, I had some problems. In composer.json, I had to use ~7.0 but I had used dev-laravel-5 for 2 other installs.

The composer update worked. But when I tried to install the package, I get this:

  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'AdamWathan\EloquentOAuthL5\EloquentOAuthServiceProvider' not found  

The provider and alias are in app.php as they appear on your site.

**Comment by adamwathan** [comment]
The `dev-laravel-5` branch is gone now, and there is no `~7.0` release of this package. It sounds like maybe you are explicitly requiring `adamwathan/eloquent-oauth`, rather than this wrapper package which is `adamwathan/eloquent-oauth-l5`. Right now the latest releast is `0.2.0`, so I would recommend this in your composer.json:

```
{
    // ...
    "adamwathan/eloquent-oauth-l5": "0.2.*",
    // ...
}
```

That will pull in this package, which will pull in `~7.0` of `adamwathan/eloquent-oauth`.

The base `eloquent-oauth` package has no service providers or anything anymore, that stuff has been split out into separate Laravel 4 and Laravel 5 wrappers (this repo is the Laravel 5 wrapper) because the installation process was too different for the two versions.

**Comment by jerauf** [comment]
Ok. When I run the command php artisan eloquent-oauth-l5:install, it tells me that there are no commands defined in the "eloquent-oauth-l5" namespace.

**Comment by adamwathan** [comment]
The command is `php artisan eloquent-oauth:install` but that is an inconsistency, so will update that in a future version, thanks for pointing that out.

**Comment by jerauf** [comment]
I get the error:

There are no commands defined in the "eloquent-oauth" namespace.

**Comment by adamwathan** [comment]
Are you registering this service provider?

`AdamWathan\EloquentOAuthL5\EloquentOAuthServiceProvider`

I just created a brand new 5.1 project and the command shows up for me. I've pushed the repo, maybe you can spot a difference between this project and yours:

https://github.com/adamwathan/eloquent-oauth-l5-example

**Comment by jerauf** [comment]
Ok. Thanks.

When I publish the config, it works. But when I go to auth/login, I get a file not found.

**Comment by adamwathan** [comment]
Can you give more information about the error? What line of code is failing, and what is the file that isn't found?

**Comment by jerauf** [comment]
Thanks for being so responsive. It seems like 5.1 changed how this is
installed as I didn't have any problems under 5.0.

Here is the error:

NotFoundHttpException in RouteCollection.php line 143

And I'm trying to go to mysite.com/auth/login.

**Comment by adamwathan** [comment]
It sounds like maybe the route hasn't been defined correctly.

Can you post the code from your routes file that should be responding to that route?

**Comment by jerauf** [comment]
Yeah. It matches your example.

Route::get('/', function () {
    return view('welcome');
});

**Comment by adamwathan** [comment]
Ah ok well you need a route defined for `auth/login`, the example I pushed up isn't fully complete, just getting the package installed.

Are you new to Laravel? Defining a route for mysite.com/auth/login would look like this:

```
Route::get('auth/login', function () {
    // do some stuff
});
```

As it stands you only have your home `mysite.com/` route defined. You should be able to follow the rest of the usage instructions here to get going with the package:

https://github.com/adamwathan/eloquent-oauth#usage

Read up on how routing works in Laravel in general if you're not familiar: http://laravel.com/docs/5.1/routing

**Comment by jerauf** [comment]
Hey - I'm not new to Laravel. Last time I installed your package (last
week), I didn't have to do that. It was just there.

**Comment by adamwathan** [comment]
The package has never created any routes, you need to define the routes in your routes file manually.

**Comment by adamwathan** [comment]
The installation process has changed since this video, but all of the other setup (routes and stuff) is still the same:

https://vimeo.com/120085196

**Comment by jerauf** [comment]
Ok. Thanks. I appreciate the help very much.

**Comment by adamwathan** [comment]
No problem! Good luck, if you run into any other issues let me know, always looking for ways to improve the package.

**Comment by manimadhup** [comment]
Hi,I am registering with keycloak authentication ....
I am getting the error -- No provider has been registered under the alias 'keycloak' ----
I have done the same setting what you have told....I am calling the function from route...
and in the controller I am calling SocialAuth::authorize('keycloak'); ...I am getting the above error....

**Comment by adamwathan** [comment]
This package only supports the following providers:

- Facebook
- GitHub
- Google
- LinkedIn
- Instagram
- SoundCloud

...as per the documentation here: https://github.com/adamwathan/eloquent-oauth#supported-providers
