### ISSUE TITLE
ModelNotFoundException on user

### ISSUE THREAD

**Issue by syphernl** [adamwathan/eloquent-oauth-l5#8]
If a user logs in which hasn't logged in before I'm getting a `ModelNotFoundException` thrown by `vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php`. 
The UserStore for this package deals a lot with the user aspect, so perhaps it should also catch errors like these?

**Comment by adamwathan** [comment]
Yikes this shouldn't be happening, it should be creating a user if it detects the user has never logged in before. Are you able to reproduce in a sample project that you can upload?

**Comment by syphernl** [comment]
Unfortunately that'll be a tad difficult since both the oAuth server and client application are on internal servers and rely on internal services to function.

It's a bit odd since it does work fine on our (internal) QA server but when I try it in my Vagrant box I'm getting this error. The codebase is exactly the same though.

**Comment by adamwathan** [comment]
Hm :/ Without being able to reproduce here I'm not sure what to do. Somehow, this `userExists` check must be coming back as true, but there's no user in the `users` table:

https://github.com/adamwathan/eloquent-oauth/blob/master/src/Authenticator.php#L28-L31

Can you manually inspect the `oauth_identities` table and see if there is an entry there that is pointing to a `user_id` that doesn't actually exist in your `users` table? Maybe a user was deleted without deleting their corresponding OAuth identity, and trying to log them in again is causing this error?

If that's the case I'll have to think if I should be trying to work around that in this package. Maybe should use a real foreign key constraint in the `oauth_identities` migration and delete on cascade.
