### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by limatheus** [adamwathan/eloquent-oauth-l5#9]
Hi, first i need say thank you for this awesome package.

I'm using Laravel 5.1 fresh installation to test your package.

After authorization (authorization OK), when i'm redirected back to my app  and i got a blank screen... nothing happens.

I try use dd() to debug, but always returns a  blank screen, can you help-me?

My route

``` php
Route::get('facebook/authorize', function() {
    return OAuth::authorize('facebook');
});

Route::get('facebook/login', function() {

    //dd(OAuth::login('facebook'));

    OAuth::login('facebook', function($user, $details) {
        dd($details);
    });
});
```

Thank you so much

**Comment by adamwathan** [comment]
Hey Matheus, sorry you are having issues!

First thing to rule out, if you just do something like this:

``` php
Route::get('facebook/login', function() {
    dd('here');
});
```

...and visit `/facebook/login` manually in your browser, do you see the debug message?

If so, try visiting `/facebook/authorize`, letting the redirect happen, and make sure you are still seeing it. If not, double check that the redirect is hitting the correct end point and there's not a silly typo there or anything.

Failing that, the one thing I noticed that was missing in your code is that you need to redirect somewhere or render a view after that authorization happens. If you don't return anything from the closure in the route, you'd get a blank screen because Laravel has nothing to render, so that might be the problem too.

Make sure you redirect the user to whatever route they are supposed to see after logging in:

``` php
Route::get('facebook/login', function() {
    OAuth::login('facebook');
    return redirect('/dashboard'); // or home, index, welcome, whatever your main logged in endpoint is
});
```

Hopefully that helps solve your problem, if not let me know and we can figure it out!

**Comment by limatheus** [comment]
Thank you so much Adam!

Is working in part now =)

I just delete everithing and create a new fresh installation, after i run composer dumpautoload and php artisan clear-compiled

Now i have a new problem, in the user details the e-mail is returned null

See

![Image](https://cdn.pbrd.co/images/1TnRhAnG.png)

**Comment by adamwathan** [comment]
Hmm interesting, even more interesting is that the `raw` section only has two elements!

This is what I get back

```
object(SocialNorm\User)[283]
  protected 'access_token' => string 'removed' (length=220)
  protected 'id' => string '187903669' (length=9)
  protected 'nickname' => string 'Adam Wathan' (length=11)
  protected 'full_name' => string 'Adam Wathan' (length=11)
  protected 'avatar' => string 'https://graph.facebook.com/v2.3/removed/picture' (length=49)
  protected 'email' => string 'example@example.com' (length=22)
  protected 'raw' => 
    array (size=11)
      'id' => string 'removed' (length=9)
      'email' => string 'example@example.com' (length=22)
      'first_name' => string 'Adam' (length=4)
      'gender' => string 'male' (length=4)
      'last_name' => string 'Wathan' (length=6)
      'link' => string 'http://www.facebook.com/removed' (length=33)
      'locale' => string 'en_US' (length=5)
      'name' => string 'Adam Wathan' (length=11)
      'timezone' => int -4
      'updated_time' => string '2015-06-19T16:57:51+0000' (length=24)
      'verified' => boolean true
```

Is there any chance you denied certain permissions during the Facebook authentication process?

**Comment by limatheus** [comment]
No, I don't make any change in the authorization process.

I put public_profile, email on the scope[], but don't work too..

I observe your return and the type is a object `SocialNorm\User` whyle my is `User`

I deleted the project and recreate it many times and the return is the same, using the Socialite  the return is the expected... all profile informations are returned.

I liked so much your package , i followed every instructions but i can't make it works right.

Thank you Adam, for your time and patience.

**Comment by adamwathan** [comment]
Ah man that's annoying. The object is likely the same, the `dd` is just not showing the namespace I bet.

Is there any chance you can create a small Laravel app that is reproducing the issue and add me as a collaborator or make it public? I'll gladly pull it down and try to help debug it.

I'm going to compare the Socialite code to mine and see if I'm missing a scope or anything that might make things not work correctly for certain accounts.

**Comment by adamwathan** [comment]
I think I've found the problem, it was an update in the 2.4 API that might be affecting 2.3 in some cases or something. Going to update the code for 2.4 and see if that fixes it :)

**Comment by limatheus** [comment]
Yes sure,  i'm making it now =)

**Comment by limatheus** [comment]
Here is https://github.com/limatheus/laravel-oauth, a clean project with your package included.

**Comment by adamwathan** [comment]
I've released a new version of the `socialnorm/facebook` package to properly support the 2.4 Graph API, can you blow out your vendor folder, do a fresh `composer update` and see if you get any different results?

**Comment by limatheus** [comment]
Ya ha!

That's it, updating  the API version to 2.4 solve the problem, now the e-mail is returned too =D

Thank you so much Adam!

**Comment by adamwathan** [comment]
Awesome!
